//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Alumno
    {
        public int idAlumno { get; set; }
        public int legajo { get; set; }
        public int Persona_IdPersona { get; set; }
    
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
